version: '3.7'


services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: alway
s    ports:
      - "20021:21"
      - "30000-30009:30000-30009"
    volumes:
      - fbg-ftp-data:/home/twh/fbg-ftp-data
    environment:
      - FTP_USER=twh
      - FTP_PASS=19921120
      - LOG_STDOUT=1

volumes:
  fbg-ftp-data